[workspace]
members = [
    "artifice", # main library
    "artifice-main", # executable
    "artifice/macros", # macros
    "kyute",    # user interface library - widgets and application architecture
    "kyute-shell",    # user interface library - windowing, drawing and system integration
]
exclude = ["ext/druid", "ext/directx-rs"]

[profile.release]
debug = true
