[workspace]
members = [
    "artifice", # main library
    "artifice-main", # executable
    "artifice/macros", # executable
    "kyute",    # the user interface library
    "kyute/macros",    # user interface codegen macros
    "veda",     # state management store library
    "veda/macros", # macros for veda
]
exclude = ["ext/druid", "ext/directx-rs"]

[profile.release]
debug = true
