[workspace]
members = [
    "artifice", # main library
    "artifice-main", # executable
    "artifice/macros", # executable
    "kyute",    # the user interface library
    "kyute/miniqt-sys",    # lightweight Qt wrapper
    "kyute/macros",    # user interface codegen macros
    "veda",     # state management store library
    "veda/macros", # macros for veda
]
exclude = ["ext/druid", "ext/directx"]

[profile.release]
debug = true
