[package]
name = "artifice-gfxbase-macros"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = "2018"

[dependencies]
quote = "1"
syn = "1"
darling = "0.10.2"
proc-macro2 = "1"

[lib]
proc-macro = true
