[package]
name = "artifice-opengl"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
edition = "2018"


[dependencies]
glutin = "0.24"
winit = "0.22"
artifice-gfxbase = { path = "../artifice-gfxbase/" }
